### ISSUE TITLE
Trying to understand how to implement a sensor

### ISSUE THREAD

**Issue by sprior** [mikejac/node-red-contrib-google-smarthome#115]
Using this package I was able to get on/off switch device support working in one evening, I am really happy about that - thanks.

Encouraged by that success I'm trying to understand how to work with the Sensor node.  As far as I understand this would be used to be able to display a value in the Google Home App.  As a test I set up an Inject node which injects a message of msg.payload = {       temperatureAmbientCelsius: 17.5,       humidityAmbientPercent: 60     }.  Not sure what to use for the topic so I left it blank.  Then I set up the output of the Inject node to the input of a Sensor node, named it HappinessIndex (just for giggles) and also set the output topic to HappinessIndex, then deployed.

Now when I go into the Google Home app I can see an icon for the HappinessIndex which says it's a device type: Sensor, but doesn't display the value.

So I seem to be pretty close, but I'm not sure what I'm missing or what this should even look like when working.

**Comment by ckhmer1** [comment]
Have you asked to Google "give me the HappinessIndex temperature"?

**Comment by sprior** [comment]
I get a response that it can't reach the Happiness Index right now.

**Comment by sprior** [comment]
I also notice that I have "If msg arrives on input, pass through to output" checked in the Sensor node and connected a debug node to it's output, but when I press the button on the Inject node I get a message that the msg was successfully injected, but I don't see anything in the debug output.

**Comment by Caprico85** [comment]
> Encouraged by that success I'm trying to understand how to work with the Sensor node. As far as I understand this would be used to be able to display a value in the Google Home app.

Unfortunately not. Sensors and windows (and probably other devices) only show a general information page with their room assignments in the Google Home app. But they don't show their measured values. This has to be implemented by Google. There is nothing we can do about that.

It is an ugly solution, but you can probably use a thermostat node. Thermostats show their current temperature in the app. But they don't support humidity. Or you can switch to an external dashboard like node-red-dashboard altogether.


> I get a response that it can't reach the Happiness Index right now.

This should not happen. There should be no general connection errors, since you are able to use your switch. Seems to be related to the sensor. Do you get any messages in Node Red's debug panel or in the debug log?

**Comment by ckhmer1** [comment]
Hi,
just an update, the Thermostats supports the humidity and temperature, but You must use the Generic Google Device node, select the thermostat type and enable the "Humidity Settings", see image below:

![image](https://user-images.githubusercontent.com/2863760/118521991-d8039900-b73b-11eb-9058-b4507fce03a7.png)
