### ISSUE TITLE
Window devices not displaying status

### ISSUE THREAD

**Issue by merlinschumacher** [mikejac/node-red-contrib-google-smarthome#12]
When I add a window it only shows a generic icon and i cant see it's status in the home app.

![Screenshot_20200106-013519_Home](https://user-images.githubusercontent.com/7475989/71788717-13109b00-3025-11ea-95c9-9cd05600a7d3.jpg)

**Comment by Caprico85** [comment]
Unfortunately this has to be fixed by Google. See https://support.google.com/googlenest/thread/14233339?hl=en or https://support.google.com/googlenest/thread/19329872?hl=en

You can currently only control windows with voice. It also works on the Nest Hub (Smart Display), but not in the app.

Google also supports doors directly, see https://developers.google.com/assistant/smarthome/guides/door, though not implemented in node-red-contrib-google-smarthome yet. I don't know if doors work better in the app.

**Comment by merlinschumacher** [comment]
Thanks for the information. I tried using the door type, but it's identical.
