### ISSUE TITLE
Google Device issues 

### ISSUE THREAD

**Issue by limpens** [mikejac/node-red-contrib-google-smarthome#122]
Using node-red-contrib-google-smarthome version 0.0.63.

First issue; I attempted to use the 'doorbell' device type.
Adding it to a flow results in getting an _400, Request contains an invalid argument_ response back from Google.

Additionally, when changing a device type in the 'Google Device', it appears previous traits are not removed.
This might be by-design but it looks weird in the device properties and debug-logging.

For example adding a google-device, first selecting type 'curtain' and then selecting 'television' ends up with mixed traits.
The Google home app shows an TV icon, but the actions on pressing the power-symbol report 'off' and 'closed' in the interface.

**Comment by ckhmer1** [comment]
Hi,
I'm not able to reproduce the problem.
The device type is not enough to replicate the configuration, I need at least the configuration of all enabled traits, but could be not enough to reproduce the problem.

Regarding Your question related to changing the device type, because Google allows mixing traits in the device, it's the user's responsibility to select the right traits matching his/her needs. If the user selects a device type, does some configuration with several traits, then changes his/her mind, and wants to change only the device type, We cannot know if the already configured traits are still needed on not. It depends on the situation.

If you want to configure a new node by scratch, just remove the old one and create a new one, this is the correct way to manage this scenario.

Claudio

**Comment by limpens** [comment]
Alright, interpretation error on my end. I selected 'recommend traits' but didn't enter any values for any of the parameters. Adding an 'on/off' trait to the device solved the error.

I understand your response about the issue with the trait mixing/selection.  Removing / adding a node is not a problem.

Regards, Eric
