### ISSUE TITLE
SSL certificates in Management node.

### ISSUE THREAD

**Issue by FireWizard52** [mikejac/node-red-contrib-google-smarthome#207]
This is more a question, than an issue or a problem.

I run Node RED and so also Google Smarthome on a Raspberry Pi in my local network. In the router/firewall/server I have no open ports forwarded to this Raspberry Pi. For the server I have Let's Encrypt certificates installed. In order to use Google Smarthome I have to use valid certificates and therefore I have copied the complete directory to a created directory under .node-red on the RPi.

![Screenshot_Smarthome SSL_Offload](https://user-images.githubusercontent.com/46283323/145856314-fc51204f-5208-4812-ba73-6b6f9cdf8ce0.png)

As we know, we have two options:
1, Tick the checkbox "Use external SSL offload".
2. Insert the complete path to the directory with the certificates.

I choose the second option and that works fine, but requires that I copy each 90 days new certificates to that directory.

Unfortunately I cannot find a guideline on how to use the first options. so that I can make the certificates discoverable on the server.
Is there anyone, who use the first options and is willingly to give a guideline?

Thanks in advance.

Regards

**Comment by Paul-Reed** [comment]
Can't help with option 1, but have you considered using [Certbot ](https://certbot.eff.org/)which manages certificate renewals?

I wrote a [guide to set this up for node-RED users](https://discourse.nodered.org/t/node-red-ssl-using-letsencrypt-certbot/17606) which may help you with option 2.

When you have renewed the certificates, you will also have to stop and restart the smarthome server to read in the new certificates by injecting `restart_server` into the management node ( I restart every Sunday at 4am).

**Comment by FireWizard52** [comment]
Thank you Paul for your quick response.

> have you considered using Certbot which manages certificate renewals?

Yes I use it, as my server, which is actually also een gateway/firewall has the option to use Let's Encrypt and also takes care of the renewal.
For your information, it is a ClearOS (based on CentOS/Red Hat) distribution running on a HP MicroGen8 server.
https://documentation.clearos.com/content:en_us:7_ug_lets_encrypt

I believe this will work, although I installed it recently (November 6), but afterwards I have to copy the certificates from the ClearOS. In the meantime I already created a Node Red flow, that checks every day if the certificate is renewed and, if so, copies the files (rsync) from the ClearOS server to the Raspberry Pi and restarts the server.

This process is running fine, but I had a little hope that it could be done in a simpler way and that Google Smarthome use the certificates directly from the server,  
I check every day at 10 a.m., as I do not want that something fails in the night, when I'm sleeping.

Thank you anyhow for your response and the guideline, which I had seen.

Regards

**Comment by Paul-Reed** [comment]
Agree, it would be good to get some more information about using external SSL offload, but if it is not a viable option, you could automate the process by using certbot's renewal hooks, instead of running a node-RED flow everyday to copy the certs.

If you create a bash script to copy across the certificates and drop it in `/etc/letsencrypt/renewal-hooks/deploy` (path depending upon system), the script will be executed automatically **only** whenever the certificate is successfully renewed.
If the renewal fails for whatever reason, the post-hook will not run the script.

**Comment by FireWizard52** [comment]
Thank you Paul for your suggestion.

> you could automate the process by using certbot's renewal hooks, instead of running a node-RED flow everyday to copy the certs.

No, I do not run the Node RED flow everyday to copy the certificates.
I only run a flow everyday to check, whether the certificate has been renewed. If not, nothing happens. And only if it has been renewed, I copy (rsync) the certificates to the Raspberry Pi to the correct directory and restart the server to read the new certificates.
However the suggestion of that bash script is a good one. I will look to that.
But what remains, is that I have to check whether the script has been executed or not. If so, I have to restart the server.
But what you said,that the script is not executed, if the script is not successfully renewed. Is that possible?

On the other hand, I have seen @Caprico85 configuration at #188, that he has ticked the box "Use external SSL offload".
So perhaps he knows, what the requirements are.

**Comment by Paul-Reed** [comment]
> But what you said,that the script is not executed, if the script is not successfully renewed. Is that possible?

No, I said;

> the script will be executed automatically only whenever the certificate is successfully renewed

Any scripts in the `renewal-hooks/deploy` directory are run automatically, only if the certificate renewal has taken place and has been successful.
So if for example Certbot attempts to renew the certificate, and your internet is down, certbot will not run scripts in the `renewal-hooks/deploy` directory because the cert renewal has failed.
If however the cert renewal was a success, then certbot will run the scripts.

If you want the smarthome server to restart after reading in the new certs, add that function to the same bash script, after copying the certs over.

**Comment by FireWizard52** [comment]
It is an idea and maybe more reliable than that NR pulls the certificates from the server. I look into that
But I'm still interested in the other option. So let's wait if someone responds with a good suggestion for that solution.

Thanks anyhow for the suggestion

**Comment by Paul-Reed** [comment]
I'll bail out now, but just for info, this is the bash script that I'm running in the `renewal-hooks/deploy` folder of a Oracle remote server.
```
#!/bin/bash

domain=nodered.digitalnut.co.uk
node_dir=/home/opc/.node-red/certs
node_user=opc

cp /etc/letsencrypt/live/$domain/*.pem "$node_dir"/
chown $node_user "$node_dir"/*.pem
node-red-restart
```

Regards

**Comment by FireWizard52** [comment]
Thanks Paul, I saw it already in your tutorial.

**Comment by ckhmer1** [comment]
I'm sorry but I don't understand,
if You have a different server renewing the certificate, You just need to have a reverse proxy on it (like Nginx, Apache HTTPD, or others) redirecting the /smarthome path to the Node-RED. In Node-RED just disable the SSL (You can also use the same Node-RED port without starting a new WEB server to a different port)

**Comment by Caprico85** [comment]
"Use external SSL offload" means the smarthome service will speak HTTP instead of HTTPS. You need this if you run Node-RED behind a reverse proxy.

In a normal setup you forward incoming HTTPS traffic from your router directly to Node-RED. This means Node-RED has to handle the SSL encryption itself. The other way is using a reverse proxy. In this case incoming HTTPS is forwarded from your router to the reverse proxy. The proxy decrypts the SSL traffic and then forwards the decrypted traffic to the backend services (Node-RED in our case). This way, the backend services don't have to deal with SSL and renewed certificates.

I use Traefik as reverse proxy. Traefik handles all SSL related stuff, it adds password protection and then it forwards traffic to the backend services (example.com/node-red goes to Node-RED, example.com/grafana goes to Grafana, example.com/smarthome goes to the smarthome service, ...). This way the backend services are all reachable on the same port and they don't need any special configuration regarding password protection and SSL certificates. The whole configuration is handled entirely inside Traefik. And most importantly, Traefik also does automatic certificate renewal of Lets Encrypt certificates without having to copy certificates around or having to restart a service.

On the other hand, Traefik is harder to setup. Traefik itself and the other services should run as Docker containers. This comes with its own set of problems. For example Node-RED running in a Docker container can't easily access hardware devices like GPIO ports.

**Comment by FireWizard52** [comment]
Thanks @Caprico85  and @ckhmer1 for the detailed answer.
Now I understand the intended use of the checkbox "Use external SSL offload". This is only applicable in case of a reverse proxy.

I suggest to extend the text  "Use external SSL offload" with a guidance text "in case of reverse proxy" and/or  add @Caprico85 's text to the Readme text.

Thanks for your answers.
Regards

**Comment by Caprico85** [comment]
I changed the Readme to explain SSL offloading a bit better.
