### ISSUE TITLE
I messed up my installation somewhere

### ISSUE THREAD

**Issue by bartbutenaers** [mikejac/node-red-contrib-google-smarthome#218]
Hi guys,

I first tried to solve my issue via the Discoure community (see [here](https://discourse.nodered.org/t/completely-stuck-with-node-red-contrib-google-smarthome/55709)), but no luck so far...

A few months ago I setup this node to control some devices in my house, and it work great!  Some time afterwards it didn't work anymore: as soon as I spoke a command on my Android Samsung smartphone, I got browser search results instead of the action being executed.  Found on the web that lots of users had the same problem (not in Node-RED!!), but no solution. 

So I tried LOTS of things last weekend to solve it, but no luck.  And I must have something terrible stupid, because my Google Home app doesn't show me any devices anymore:

![image](https://user-images.githubusercontent.com/14224149/147449575-352c67e9-4050-4d2f-ba11-c63dbc2f4eb6.png)

I am now wondering if this (= the fact that google did a web search instead of executing my actions) could have been caused by the renewal of my LetsEncrypt certificates?  Some time I go I have created a [pull-request](https://github.com/node-red/node-red/pull/2551) to load my renewed certificates (from the prevkey.pem file) automatically in Node-RED without having to restart Node-RED, but I had completely forgotten that I should restart automatically your webserver also when my privkey.pem file is updated...  

So I am now completely stuck.   Would really appreciate some help!

1. When I call the check url on port 3001, I get this page:

   ![image](https://user-images.githubusercontent.com/14224149/147450334-31393bfb-99ce-48dd-99d9-528db1326d0b.png)

   Not sure which username and password needs to be entered here?

2. When I go to the logs of my project (let's call it xxxx):
   ```
   https://console.cloud.google.com/logs/query;query=resource.type%3D%22assistant_action_project%22?project=xxxx
   ```
   Then I see only sync requests arriving until last weekend:

   ![image](https://user-images.githubusercontent.com/14224149/147450907-37b7cebd-0c13-4f78-9217-299b14b44ecd.png)

   And indeed when I added a new device last weekend (by adding new nodes of this repo to my flow), they indeed appeared correctly in my Google Home app after those (automatic) sync requests.

   So I assume I cannot see in those logs why my voice commands didn't work in the previous weeks (e.g. due to a expired LetsEncrypt certificate)??

3. When I send a request_sync or report_state topic to the manager node, I get this error:
   > HttpActions:requestSync(): no user logged!

   I get the same error after I deploy my flow.  When I debug your node, I always arrive at the red arrow statement:

   ![image](https://user-images.githubusercontent.com/14224149/147451753-e236a45b-0b99-4f96-93de-9ab8d1592f75.png)

   So the sync requests are not being send, due to following condition:

   ![image](https://user-images.githubusercontent.com/14224149/147451839-0ee0a305-7f82-4012-9f30-c14cf026bc2c.png)

   But unfortunately I have no clue how this works...

Would be very nice if you could give some other tips of stuff I could test to find the root cause.

Thanks a lot !!
Bart

**Comment by Caprico85** [comment]
Hi Bart,

if your devices don't show up in the app anymore, it is usually related to problems with account linking.

This would also explain why Google started browser searches. If Google doesn't know your devices anymore, it doesn't know what you are referring to if you say "turn on the light". Sometimes it answers with "You haven't setup this device yet". And sometimes it starts a browser search, trying to be helpful on how to turn on lights in general.

 I've seen problems where Google disconnected my account after it repeatedly failed to renew access tokens. Maybe Google disconnected your account too after your certificate issues.

Strange thing is that some devices still showed up in your app. If your account is disconnected, there nothing should be displayed in the app.

Anyway, first thing I would try is unlinking the account, delete the auth storage to clear out old authorizations and then relink your account:

1. Follow the instructions in [Setup account linking](https://github.com/mikejac/node-red-contrib-google-smarthome#setup-account-linking) up to the point where you see the list of all projects. If your project is listed on top of the list under "Linked services", tap it and select "Unlink account". **Don't relink it yet**.
1. Stop Node-RED.
2. Connect to your host via SSH/SFTP, go to Node-RED's user directory (where your settings.js, flows.json etc. are stored) and  delete all files named google-smarthome-auth-*.json.
3. Restart Node-RED
4. Follow the instructions in [Setup account linking](https://github.com/mikejac/node-red-contrib-google-smarthome#setup-account-linking) again, this time linking your account normally.


---

**Regarding http://.../check**

>    Not sure which username and password needs to be entered here?

If you are using username/password based login, it's the username and password you set in your config. If you are using Google Sign-In ... I don't know either 😄. This page was written by @ckhmer1. I guess, username is the email address. But i haven't found which password to use.

---

 **Regarding Google Cloud logs**

> So I assume I cannot see in those logs why my voice commands didn't work in the previous weeks (e.g. due to a expired LetsEncrypt certificate)??

Errors may have not been logged because your account was already disconnected by then. So Google didn't know which project the errors should be logged into. Or, as Google started browser searches, it didn't understood you wanted to control your smart devices at all, so it saw no reason to log into any smarthome project.

**Comment by bartbutenaers** [comment]
Hello @Caprico85,

I appreciate your fast and extensive feedback!!  Going to experiment tonight with the account unlinking...

But to get a bit more understanding of the subject: are the sync errors (`no user logged`) related to the account linking?  I thought that account linking is between the Google Home app (on the Android device) and the Google servers.  But is it perhaps also important between Node-RED and the Google servers?  Noob question...

**Comment by bartbutenaers** [comment]
@Caprico85,
I think that I have already unlinked my device last weekend...
Because my test project isn't anymore in the section 'linked services':

![image](https://user-images.githubusercontent.com/14224149/147507240-3640db78-e3b2-4193-b91f-145758f98c08.png)

When I click on my (test) project in the list, it seems to navigate to port 3001 and display this screen:

![image](https://user-images.githubusercontent.com/14224149/147507298-7e134e6a-d4fa-4e7f-9384-ef3992ee0402.png)

But when I click that white login to Google button, I get a grey screen and nothing happens :-(

**Comment by bartbutenaers** [comment]
Morning @Caprico85,

I have spend some more hours last night to do some troubleshooting, but I got nowhere.  The people from Google make amazing stuff, but they seem to think that all their users have an IQ above 180...

Must admit that I am VERY impressed by the developments of this node.  Don't know how you guys managed to get it running.  Very impressive work!!!  Thanks for all the time you take to implement this, and answer stupid questions...

Had hoped that I could have found some troubleshooting improvements, which I could share here.  But this morning I have decided to setup everything from scratch.  And now it seems to work again!  Will add here some of my steps, so hopefully you can use it to improve this node a little bit better...

1. I executed all the steps from the readme page.  But this time I have used username/password to make things a bit more simple.

2. Then my check url test failed:
   ```
   GET oauth: ERROR: client_id xxxxxx invalid
   ```
   I checked it over and over again, but the client_id was correct.  
   Then I saw this in my startup log:
   ```
   28 Dec 07:10:37 - [info] Started flows
   SmartHome:Start(listen): listening at :::3001
   28 Dec 07:10:37 - [error] [googlesmarthome-client:VoiceControlNodeRedClient] SmartHome:Start(): err:Error: listen 
   EADDRINUSE: address already in use :::3001
   ```
   I have restarted your webserver and rebooted my Raspberry, but same issue.  So at the end I have done following:
   + Removed my old config (since I had two config nodes).
   + Seemed I had forgotten to use the new config in my Shutter node, so I have selected there also my new config node.
   + Removed the old json google-smarthome-auth....json file from my .node-red folder.  
   
   Then the port issues was solved and my check was successfull.
   
   Unfortunately I don't know which of my 3 actions solved it.  _**But it seems to me less confusing that only 1 webserver is started, i.e. the one that has been selected in the Management node**_.  Because you have no visual indication in the flow that the port is in use, when you select another config in one of the other nodes...  Or e.g. add a validator to every node, and show a red triangle in the flow when they use a config that differs from the one selected in the config node (although not sure if that is possible...).
   
3. In the step of adding an existing device in my Google Home app, my new test app appeared and logon via my credentials worked without problems:
 
   ![image](https://user-images.githubusercontent.com/14224149/147542568-ad4c7865-5dff-461c-bfd6-3e3a5185c4d2.png)

   And shortly afterwards my test app was moved automatically to the "Linked Services" section:

   ![image](https://user-images.githubusercontent.com/14224149/147543310-bc20df52-bf6f-40ac-9643-180269b99743.png)

4. When I added a new Shutter node to my flow, the device automatically showed up after a few seconds in my Google Home app:

   ![image](https://user-images.githubusercontent.com/14224149/147542975-301106e8-9327-49f5-b25f-02b847bab1a0.png)

Hopefully my screenshots might be of any use, for noob users like me starting with this...

You can close this issue, unless you need some extra information from me.

Thanks!!! 
Bart

**Comment by bartbutenaers** [comment]
It works also on my wife's phone to control some devices in our home.  Not having to use the Node-RED dashboard is a major breakthrough for my personal home automation.  This is an awesome node !!!!!!

**Comment by Caprico85** [comment]
I'm glad you got it working.


> But it seems to me less confusing that only 1 webserver is started, i.e. the one that has been selected in the Management node. Because you have no visual indication in the flow that the port is in use, when you select another config in one of the other nodes... Or e.g. add a validator to every node, and show a red triangle in the flow when they use a config that differs from the one selected in the config node (although not sure if that is possible...).

I agree. Currently each config starts its own webserver. If they use the same port, they collide. I'll experiment a bit on what can be done.


Just to answer some remaining questions, in case it may help others:

&nbsp;

> But to get a bit more understanding of the subject: are the sync errors (`no user logged`) related to the account linking?

During account linking we generate oAuth tokens. These are sent to Google and also stored on disk. If the file with the tokens (google-smarthome-auth-*.json) gets deleted, our service sees it as "no tokens found => user has not logged in".

This could also explain your problems after the certificate renewal. Tokens expire after some time. If Google cannot connect to your service to refresh tokens (e.g. because of failed certificates), Google may kick you.

&nbsp;

> I thought that account linking is between the Google Home app (on the Android device) and the Google servers. But is it perhaps also important between Node-RED and the Google servers? Noob question...

The app is more or less only a GUI to the Google servers. It always sees the same as the Google servers and doesn't need any special linking (or rather, linking was already done when you set up your phone using your Google account).

Account linking connects the Google servers to the device manufacturers servers. Let's assume you just bought a Philips Hue lamp. Philips as the device manufacturer has registered as a smarthome provider with Google earlier. Philips also has their backend service running on their server. During account linking you say "Dear Google, I use lamps from Philips Hue. The credentials to my Philips account are bart/12345678. So, please Google, connect your systems to the Philips servers and control my new lamps over there".

The same applies to you. You as the "device manufacturer" registered as a smarthome provider using the Google Actions Console. You have your backend service running on your server (which is Node-RED running on your RasPi). During account linking you say "Dear Google, I use lamps from 'Barts Smarthome service'. The credentials are bart/12345678. So, please Google, connect your systems to Bart's service and control my lamps there".

**Comment by bartbutenaers** [comment]
For completeness, if somebody is ever wondering how I solved the certificate issue today.  When a new LetsEncrypt certificate is installed (in my cert.pem file) via my [node-red-contrib-letsencrypt](https://github.com/bartbutenaers/node-red-contrib-letsencrypt) node, I now automatically restart the webserver of the smarthome node:

![image](https://user-images.githubusercontent.com/14224149/147584574-ae298c58-1aa6-407c-90bf-e4e9cb91ac2b.png)

This way I hopefully won't run into the same problems again in the future...


P.S. @Caprico85 when I was creating this morning a new intent, I got following question:

![image](https://user-images.githubusercontent.com/14224149/147585456-cee98c0e-a636-4dc6-8bb5-107ce3c9a084.png)

I was not sure what to choose...  So perhaps you can this as an extra step (between the current steps 3 and 4):

![image](https://user-images.githubusercontent.com/14224149/147585244-7d6cb3d7-28e1-4140-bcca-5df9dc505a8a.png)

Thanks!!

**Comment by Caprico85** [comment]
You are right, Google seems to have changed their pages once again. I'll update the instructions.
