### ISSUE TITLE
Latest version (0.3.6) not available in library.

### ISSUE THREAD

**Issue by FireWizard52** [mikejac/node-red-contrib-google-smarthome#289]
The latest published version 0.3.6 is not available in the Node Red library (https://flows.nodered.org/) .
Also the Manage palette in Node Red still shows 0.3.5.

Regards

**Comment by Paul-Reed** [comment]
It's because v0.3.6 hasn't been published to npm yet.

**Comment by Caprico85** [comment]
Usually, new releases gets automatically published to npm by a GitHub action. But this time [the publish action failed](https://github.com/mikejac/node-red-contrib-google-smarthome/actions/runs/2463774065). Publishing manually fails too. I'm looking into it.

**Comment by Caprico85** [comment]
New version is now available on npm.

I have no idea what the problem was. I tried all sorts of stuff to do a manual push. Enabling and disabling 2FA, upgrading npm, Different package versions, "npm audit", other security scanners. But nothing helped. Today I simply tried to publish again on GitHub ... and it worked.
