### ISSUE TITLE
no accessToken found

### ISSUE THREAD

**Issue by Paul-Reed** [mikejac/node-red-contrib-google-smarthome#336]
Despite everything appearing to work OK, I'm occasionally getting this error reported.
It just appears at random times.

Apart from updating the Smarthome node, I haven't made any other changes recently.

![httpactions](https://user-images.githubusercontent.com/973580/198260558-4d5f7d38-071d-4261-8644-12a423fdfba6.JPG)

and the same in the node-RED log -
`27 Oct 11:21:57 - [error] HttpActions:httpActionsRegister(/smarthome): no accessToken found`

Any ideas?

**Comment by Paul-Reed** [comment]
I may have found the problem (self created!), but will give an update after further checking.
Please don't spend any time looking into this for the time being.

**Comment by Paul-Reed** [comment]
Sorry, it was problem created by me (again!!)
All good now....

**Comment by Paul-Reed** [comment]
Sorry, but I'm still getting this error in the node-RED log and the debug panel.

I thought that I'd found why it was occurring, but obviously not, and it continues to occur randomly with no specific pattern, even if I'm not issuing any voice commands.
I've had node-RED open in a browser for the past 5 hours, and I now have two such errors reported in the debug panel.

**Comment by FireWizard52** [comment]
Hello @Paul-Reed 

I have exactly the same values for "Access Token Duration" and "Report Interval" (60 minutes)
My "Request sync delay"and "set_state message delay" are not empty, but I have 2 (seconds)

No idea, why, but I think they have been there since I started to use these nodes.

I do not remember, that I have seen this error before.

**Comment by Paul-Reed** [comment]
Thanks Herman.
Mine was also set at 2 (seconds), and I thought that was the problem, so I deleted the boxes as the setup instruction say "Usually you don't need to change these values. Leave them at their default values" and the default is "0 or empty".
I didn't see an error for a day or so, but then it returned...

**Comment by FireWizard52** [comment]
Hi Paul,

I noticed also some issues with Google.

1. Since 2-3 days I noticed that the Google response is slow. It looks, like he/she has to think about it.
    While I have local-execution activated.
2. Since today local-execution fails completely, but the Google response is faster.

My first thought was, that it had something to do with the app.js file. So I uploaded the latest to Google Actions, but that did not solve the problem (once again). I do not get any response in the Chrome;//inspect console.

However I do not think that it is related to your problems.

Regards

**Comment by FireWizard52** [comment]
Hi @Paul-Reed,

Please forget my previous comment. The issue seems to have been solved automatically.
Response speed is normal (as before) and local fulfillment is also working again.
It seems that these things sometimes happens at Google.

Perhaps your issue is also caused by Google and not by Node-RED or the node-red-contrib-google-smarthome node.
But I have no idea how to solve it.

Regards

**Comment by Paul-Reed** [comment]
Yes, it could be caused by Google, but then why isn't it affecting other users?

It's more an annoyance than a problem, because everything works ok, but the error messages are a constant reminder that something is not happy, somewhere.

**Comment by Caprico85** [comment]
I finally had the time to look into this.

The message "no accessToken found" is a bit misleading. It means somebody sent you a request with an invalid access token. 

This can simply be somebody trying to hack into your smarthome. Or it may be Google doing something strange.

First thing I would do is to look into the request in detail. If you enable debugging in your management node, you will see request headers and body in your log:

```
[debug] HttpActions:httpActionsRegister(/smarthome): request.headers = {"host":"example.com:3001","user-agent":"Mozilla/5.0 (compatible; Google-Cloud-Functions/2.1; +http://www.google.com/bot.html)","content-length":"1281","accept-encoding","content-length":"1939","accept":"*/*","accept-encoding":"deflate, gzip","authorization":"Bearer XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX","content-type":"application/json","x-forwarded-for":"139.59.147.204","x-forwarded-host":"example.com:3001","x-forwarded-proto":"https","x-real-ip":"2003:c8:6f1d:4500:6ce3:44bb:583e:a748"}

[debug] HttpActions:httpActionsRegister(/smarthome): reqdata = {"inputs":[{"intent":"action.devices.QUERY","payload":{"devices":[{"customData":{"accessToken":"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX","clientId":"XXXXXXXXXXXXXX","httpPathPrefix":"/","httpPort":9999},"id":"0ac5977b0b71102d"},{"customData":{"accessToken":"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX","clientId":"XXXXXXXXXXXXXX","httpPathPrefix":"/","httpPort":9999},"id":"1f998b8914071db8"},{"customData":{"accessToken":"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX","clientId":"XXXXXXXXXXXXXX","httpPathPrefix":"/","httpPort":9999},"id":"366f093e85c829fc"},{"customData":{"accessToken":"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX","clientId":"XXXXXXXXXXXXXX","httpPathPrefix":"/","httpPort":9999},"id":"475525b40c0b1b0f"},{"customData":{"accessToken":"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX","clientId":"XXXXXXXXXXXXXX","httpPathPrefix":"/","httpPort":9999},"id":"c47b7c640826542b"},{"customData":{"accessToken":"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX","clientId":"XXXXXXXXXXXXXX","httpPathPrefix":"/","httpPort":9999},"id":"b76741bf0dbdeca7"}]}}],"requestId":"16948588037263401583"}

[debug] Auth:isValidAccessToken(): accessToken = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX" not found.

[error] HttpActions:httpActionsRegister(/smarthome): no accessToken found
```

Maybe we can already see on the requests what it is or where it comes from.


You could also have a look at the Cloud logs at https://console.cloud.google.com/logs/. If these are legitimate requests from Google and we answer with an error message, this should be logged in the Cloud logs.
