### ISSUE TITLE
Samba changes may affect paths for JSON file

### ISSUE THREAD

**Issue by RichardUUU** [mikejac/node-red-contrib-google-smarthome#447]
Long story short, there have been some changes to samba in homeassistant. What finally worked for me:

Save my Jwt Key File to: \\homeassistant\config\www\myfile.json

Configure the Management node with: Jwt Key: /homeassistant/www/myfile.json

If you're looking for a simple sanity check, import this flow and adjust the path for whatever you're using. If Node Red can read your file, you'll see it in the debug window.

```
[{"id":"85f6a652d71eaef2","type":"file in","z":"2377f432ffad2441","name":"Test File Read","filename":"/homeassistant/www/myfile.json","filenameType":"str","format":"utf8","chunk":false,"sendError":false,"encoding":"none","allProps":false,"x":1140,"y":60,"wires":[["9c932b2dc4376707"]]},{"id":"dbdd4e85de22087c","type":"inject","z":"2377f432ffad2441","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":930,"y":60,"wires":[["85f6a652d71eaef2"]]},{"id":"9c932b2dc4376707","type":"debug","z":"2377f432ffad2441","name":"debug 20","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","statusVal":"","statusType":"auto","x":1360,"y":60,"wires":[]}]
```

Cheers, Richard

**Comment by FireWizard52** [comment]
As far, as I use this Google Smarthome node in Node RED, I did not notice any issue.

You indicate that there has been changes in Samba, but
Node RED nor Google Smarthome node is using Samba.
Samba is a utility in order to establish interoperability between Unix (Linux systems and Windows). And I don't think that has impact on Home Assistant or any other Home Automation system.

You don't mention the issue(s), you have with the Google Smarthome node.

Regards

**Comment by RichardUUU** [comment]
You're right about Samba.

My issue is that the Google Smarthome node stopped working for me. The reason turned out to be that the path I had specified for my JSON file was no longer valid, I believe due to changes in Home Assistant. It took me a long tine to figure this out, and I was hoping to save someone else the trouble. 

There's nothing wrong with the Google Smarthome node, in fact it's brilliant. I thought it would be useful for someone to see the differences between the Samba path and the path required by the node.

**Comment by FireWizard52** [comment]
Hello @RichardUUU,

Okay, now it is more clear to me.

> My issue is that the Google Smarthome node stopped working for me. The reason turned out to be that the path I had specified > for my JSON file was no longer valid, I believe due to changes in Home Assistant. It took me a long tine to figure this out, and I
> was hoping to save someone else the trouble.

You believe that the path had changed, and so Google Smarthome stopped working, due to changes in Home Assistant? 
Good, that you mentioned it here, in order to help others. I believe, that you should post this message also in the Home Assistant forum, if not already done,

> Samba is how I transfer my JSON file to the Home Assistant VM, and I thought it would be useful for others to see the
> differences between the Samba path and the path required by the node.

I support the idea, to inform others about the experiences and therefore the forum made available some time ago a place to discuss these things. See "Discussions" . I recommend to use "Issues" only for issues and problems with the Google Smarthome node and to use "Discussions" for tips, questions, examples, used cases, etc.

Regards

**Comment by RichardUUU** [comment]
I created a discussion here: https://github.com/mikejac/node-red-contrib-google-smarthome/discussions/448

Thanks,
