### ISSUE TITLE
report state problem depends of language

### ISSUE THREAD

**Issue by dr-boss** [mikejac/node-red-contrib-google-smarthome#60]
What I do wrong if I receive only error after request_sync or timer sync. 
Maybe this is problem of not filed NAME but I no idea what I can write in NAME of Management node. If I fill it with name of Action from Google (from my first language) the error is:
**object
topic: "management"
payload: object
_type: "actions-reportstate"
msg: object
error: object
code: 400
message: "Request contains an invalid argument."
status: "INVALID_ARGUMENT"
deviceId: "<none>"
_msgid: "6e3568ad.7008a8"**

If I fill with name from English Invocation the error is:
**object
topic: "management"
payload: object
_type: "actions-requestsync"
msg: object
error: object
code: 403
message: "The caller does not have permission"
status: "PERMISSION_DENIED"
_msgid: "9239b788.343e88"**

**Comment by Caprico85** [comment]
These are two different error messages. The first one is from "actions-reportstate", the second one is from "actions-requestsync". 

I don't think they are related to the language or name of the management node. The name is not used anywhere so it shouldn't cause problems. My Management node is simply named "Management", with no problems so far.

Both errors originate from calls to Google's HomeGraph API. This makes it a bit hard to debug. Google's error messages are usually rather generic and unhelpful and not documented well. I'm still trying my best to help.

The second error. "PERMISSION_DENIED" usually means there is something wrong with authorization. Could be caused by wrong configuration (especially client key, client secret or JWT key) or by invalid tokens, I would recommend to:
1. Open your project in Google Actions Console, switch to tab "Test" and click "Reset test". If this does nothing, click on the "Settings" button, then disable and enable "On device testing".
2. Unlink and re-link your project in Google Home App.

The second error, "INVALID_ARGUMENT" can have multiple reasons. It can be caused by invalid authorization. So it may already be fixed with above steps. Or it can occur when an invalid device state is reported to Google (e.g. a window opened 150%). I fixed one of this errors in v0.0.42, so you may want to upgrade too.

**Comment by dr-boss** [comment]
thx, for information, I test 0.0.42 and after firsts tests I things that this version resolve reportstate problem
