### ISSUE TITLE
reqbin.com not getting OK 200 with https://

### ISSUE THREAD

**Issue by haukino** [mikejac/node-red-contrib-google-smarthome#78]
Hi,

I've followed the (very detailed) instructions to a tee, yet I am stuck somewhere.

I am running nodeRED and apache2 on a Raspberry Pi 4
Also I have added port 3001 to pass through ufw

I am getting through when I put http://mydomain.tld:3001/check, but not when on https://
Reqbin shows me Error code: 10035

If I open that page in Firefox I get:

Secure Connection Failed

An error occurred during a connection to mydomain.tld:3001. SSL received a record that exceeded the maximum permissible length.

Error code: SSL_ERROR_RX_RECORD_TOO_LONG
________________________________________________________________________________

However:
https://www.ssllabs.com/ssltest/analyze.html gives me an "A" rating
Also not sure if this is configured correctly? where should the path point to? 
![image](https://user-images.githubusercontent.com/58327926/102661594-708df100-417d-11eb-9228-4b7db016c394.png)

In the google home app on my phone I find the [test] my project, but when I tap it it just goes back to the "Linked services / Add new" screen.
I've been troubleshooting for hours now and have no Idea where to look anymore.

First I thought its the port forwarding on my router/modem. But that works fine now.
It might have something to do with the letsencrypt certificate not working on port 3001? But how do others get it to work?
Ive been through forums and other websites and struck a dead end now.
If you need to see any logs, please let me know.

Please help.

**Comment by haukino** [comment]
OK now I tried to untick the SSL offload and I got a permission denied error in the debug node. That was quickly fixed by giving rights to the privkey.pem for the node red user.

Now I get the OK 200 at reqbin. Yay!

However

I still get a blank screen when I try to add the service in Google home.

Also If I go to mydomain:3001/smarthome it says "Cannot GET /smarthome"

Where should I look?

**Comment by haukino** [comment]
Finally got it working, maybe I was to impatient or lack of sleep got the better of me.

I had a / to many in the actions url, like:
![image](https://user-images.githubusercontent.com/58327926/102664479-2ad42700-4183-11eb-9037-2a4191bb4a8c.png)

Well, hope that helps someone else in the future :-)

**Comment by Caprico85** [comment]
Glad you got it fixed.

The first problem was most probably related to a misconfiguration in Apache. Either Apache was not correctly configured to do SSL termination or (more probably) Apache was not listening on port 3001 at all. With "Use external SSL offload" disabled, node-red-contrib-google-smarthome does all of the SSL decryption itself and doesn't need a reverse proxy in front it.

> Also If I go to mydomain:3001/smarthome it says "Cannot GET /smarthome"

This is expected. /smarthome is an API endpoint called by Google and only accept POST requests. It can not be opened in a browser.

> where should the path point to?

Path can be left empty. With the path setting you can move the URL to https://example.com:3001/somespecialpath/smarthome instead of the default https://example.com:3001/smarthome.
