### ISSUE TITLE
node-red-contrib-google-smarthome two way? Or one way?

### ISSUE THREAD

**Issue by sledzik1984** [mikejac/node-red-contrib-google-smarthome#89]
Hi! 

I have problem that data send to nodes from external nodes (like input from MQTT) is not sent to Google Home App. 

When I click something in Google Home App - status is changed in node-red nodes but when I try to set something from external node - nothing happens in App on my iPhone...

**Comment by ChutneyMary** [comment]
I've noticed a similar behaviour. I think it's because the Google Home App doesn't refresh on it's own.
Make a change from an external node, then refresh the Google Home App by going into a different view (ie. click on any other device), then go back to a view where you can see the device that's been changed.

Google Home App is 'changing' the state of the particular device, but won't reflect that until a view refresh is done.

**Comment by Caprico85** [comment]
I can think of three possible reasons:

- As @ChutneyMary explained, the App doesn't update itself. Do you get the updated state after refreshing the app or when you ask "Hey Google, is <device> on?".
- The input you send into the devices is wrong, so it can't be parsed and sent to Google. Depending on how "wrong" it is, you'll see error messages in the debug panel or not.
- You are getting one of those INVALID_ARGUMENT errors, so the input you send is not accepted by Google. You should see those errors in Node-Reds debug panel.

**Comment by tkessels** [comment]
I agree with @ChutneyMary  I've seen this behaviour with other integrations as well. Since the Google Home App is not refreshing the state of the device until you interact with it. Lights seem to be special, they sometimes get updated even though I did not trigger any action in the Google Home App. But since it seems to be an Issue with the Google Home App and the onInput Handlers for lights and outlets look the same, I think this issue can be closed.
